config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  devise_for :users
  root to: "tops#index"
  resources :tops, only: :index
  resources :posts,only: [:index, :new, :create, :show, :destroy]
  resources :restaurants, only: :index
  resources :breweries, only: :index
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '20代' },
    { id: 2, name: '30代' },
    { id: 3, name: '40代' },
    { id: 4, name: '50代' },
    { id: 5, name: '60代' },
    { id: 6, name: '70代' },
    { id: 7, name: '80代以降' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '美味しい' },
    { id: 2, name: 'とても美味しい' },
    { id: 3, name: '非常に美味しい' },
    { id: 4, name: '最高に美味しい' },
    { id: 5, name: '言葉にならない' },
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '男性' },
    { id: 2, name: '女性' },
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :assessment

  with_options presence: true do
    validates :beer_name
    validates :image
    validates :style
    validates :description
    validates :bar_name

    with_options numericality: { other_than: 0, message: "can't be blank" } do
      validates :assessment_id
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 extend ActiveHash::Associations::ActiveRecordExtensions
 belongs_to :age
 belongs_to :gender

  with_options presence: true do
    validates :nickname
    validates :favorite
  end

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :age_id, :gender_id, :favorite])
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]

  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]
  before_action :move_to_index, only: :destroy

  def index
    @posts = Post.all.order('id DESC')
  
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:beer_name, :description, :style, :assessment_id, :bar_name, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    @post = Post.find(params[:id])
    redirect_to action: :index unless current_user.id == @post.user_id
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]

  def index
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/breweries/index.html.erb
<%= render "devise/shared/header" %>

<%= render "devise/shared/footer" %>

<span id="back">
    <a href="">
      <%= image_tag 'top_btn.png', data: {"turbolinks"=>false}, class: "arrow" %>
    </a>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fcbc2021</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render "devise/shared/header" %>

 <div class='top-text'>
 </div>


<div class='select-reason-contents'>
    <h2 class='title'>
        BEER DICTIONALY
     <br>
       〜新たなクラフトビールとの出会い〜
    </h2>
    <p class='title'>
      クラフトビールとの出会いは一期一会。
     <br>
      そもそもクラフトビールは醸造量が多くありません。
     <br>
      そして、同じものでも"その時"で味が変わったりもします。
     <br>
      一度飲んだら、２度と出会えない。
     <br>
      そんなビールもあるかもしれません。
     <br>
      ここでは、現在福岡で出会えるビールの最新情報、
     <br>
      過去に出会ったビールの情報を投稿し、
     <br>
     みなさんで情報を共有すると共に、
     <br>
     福岡だけの"BEER DICTIONALY"を
     <br>
     作り上げていきましょう。
    </p>
    
    <p class='post-title'>
       <%= link_to '投稿する', new_post_path , class: "post-title-btn"%>
    </p>

<div class='item-contents'>
    <h2 class='item-title'>Beer Dictionary 一覧</h2>
    </div>
    <ul class='item-lists'>
      <% @posts.each do |post| %>
        <li class='list'>
            <%= link_to posts_path(post.id), method: :get do %>
              <div class='item-img-content'>
              <%= link_to post_path(post.id) , class: "post-image" do %> 
                <%= image_tag post.image, class: "item-img" %>
                <% end %>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= post.beer_name %>
                </h3>
              </div>
          <% end %>
        </li>
      <% end %>
</div>

  <div class='bottom-text'>
 </div>

  <div class='enjoy'>
  <div class='enjoy-message'>
    <h4 class='enjoy-statement'>
          Once in a lifetime experience
          <p class='enjoy-statement-message'>
            CRAFT BEER
          <br>
             &
          <br>
             FUKUOKA
          <br>
          <p class='enjoy-statement-message2'>
          クラフトビールと福岡で素敵な出会いを
          </p>
        </h4>
    </div>
  </div>
</div>

<%= render "devise/shared/footer" %>

<span id="back">
    <a href="">
      <%= image_tag 'top_btn.png', data: {"turbolinks"=>false}, class: "arrow" %>
    </a>
</span>

app/views/posts/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%# <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">情報を入力</h2>
    <%= form_with model:@post, url: posts_path, method: "post", local: true do |f| %>

    <%# <%= render 'shared/error_messages', model: f.object %> 

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        ビールの画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
<div class="new-items">
    <div class="weight-bold-text">
        ビールの評価
        <span class="indispensable">必須</span>
      </div>
    <%= f.collection_select(:assessment_id, Assessment.all, :id, :name, {}, {class:"select-box", id:"posta-assesssment"}) %>
  </div>
    <div class="new-items">
      <div class="weight-bold-text">
        ビールの名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :beer_name, class:"input-default", id:"nickname", placeholder:"例:FUKUOKA IPA", maxlength:"40" %>
  </div>
  <div class="new-items">
      <div class="weight-bold-text">
        スタイル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :style, class:"input-default", id:"nickname", placeholder:"例:Lager・Pale Ale・etc..", maxlength:"40" %>
  </div>
  
  
      <div class="items-explain">
        <div class="weight-bold-text">
          ビールの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"詳細、感想などを自由にご記入ください。" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="new-items">
      <div class="weight-bold-text">
        お店の名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :bar_name, class:"input-default", id:"nickname", placeholder:"例:○○bar", maxlength:"40" %>
  </div>

    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', posts_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>

 

app/views/posts/show.html.erb
<%= render "devise/shared/header" %>

<div class="item-show">
  <div class="item-box">
    <div class="item-img-content">
      <%= image_tag @post.image ,class:"item-box-img" %>
    </div>
        
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">ビール名</th>
          <td class="detail-value"><%= @post.beer_name %></td>
        </tr>
        <tr>
          <th class="detail-item">スタイル</th>
          <td class="detail-value"><%= @post.style %></td>
        </tr>
        <tr>
          <th class="detail-item">ビールの説明</th>
          <td class="detail-value"><%= @post.description %></td>
        </tr>
        <tr>
          <th class="detail-item">評価</th>
          <td class="detail-value"><%= @post.assessment.name%></td>
        </tr>
        <tr>
          <th class="detail-item">お店の名前</th>
          <td class="detail-value"><%= @post.bar_name %></td>
        </tr>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @post.user.nickname %></td>
        </tr>
      </tbody>
    </table>
    <%if user_signed_in? && current_user.id == @post.user_id %>
          <%= link_to "削除", post_path(@post.id), method: :delete, class:"item-destroy" %>
      <% end %>

  </div>
</div>

<%= render "devise/shared/footer" %>

app/views/tops/index.html.erb
<%= render "devise/shared/header" %>

<div class='main'>
  <div class='title-contents'>
    <h2 class='service-title'>
    </h2>
</div>

<div class='select-reason-contents'>
    <h2 class='title'>
        CRAFT BEER
      <br>
       〜クラフトビール〜
    </h2>
    <p class='title'>
      クラフト（craft）は英語で「技術」「工芸」「職人技」などを意味する言葉。
     <br>
      クラフトビールとは、小規模醸造所がつくる多様で個性的なビールのこと。
     <br>
      醸造する豊かなその土地の風土、
     <br>
      作り手によって様々な味わいが楽しめるのが特徴です。
     <br>
      種類によって新しい驚きや発見があり、
     <br>
      クラフトビールでしか出会えない感動があります。
     <br>
      福岡にもそんな素敵なビールを醸造しているブリュワリーがあり、
     <br>
     日本各地のクラフトビールが楽しめる場所もあります。
     <br>
     福岡にはたくさんの素敵なクラフトビールたちが集まっています。
     <br>
     思い思いにクラフトビールを楽しみ
     <br>
     福岡のクラフトビールシーンを盛り上げよう。
    </p>

    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "beer-image.jpg", class:"list-pict" %>
        <h3 class='reason-list-text'>
          飲みに行こう
        </h3>
        <p class='reason-list-description'>
          福岡市内にはクラフトビールを楽しめる店が沢山。美味しい出会いを求め、素敵なお店に遊びに行こう。
        </p>
        <p class='Resutoran'>
        <%= link_to 'Restaurant', restaurants_path %>
        </p>
      </li>
      <li class='list'>
        <%= image_tag "brewery-image.jpg", class:"list-pict" %>
        <h3 class='reason-list-text'>
          醸造所を知ろう
        </h3>
        <p class='reason-list-description'>
          福岡県にはクラフトビールを醸造しているBreweryが沢山。お気に入りのブリュワリーを応援しよう。
        </p>
        <p class='Resutoran'>
        <%= link_to 'Brewery', breweries_path %>
        </p>
      </li>
      <li class='list'>
        <%= image_tag "kanpai-image.jpg", class:"list-pict" %>
        <h3 class='reason-list-text'>
          共有しよう
        </h3>
        <p class='reason-list-description'>
          実際に飲んでみて、美味しかった、面白かった等、ビール情報を投稿してみんなで楽しみましょう。
        </p>
        <p class='Resutoran'>
          <%= link_to 'Dictionary', posts_path %>
        </p>
      </li>
    </ul>
</div>

<%= image_tag "fukuoka1.jpg", class:"oohori" %>

<div class='enjoy'>
  <div class='enjoy-message'>
    <h4 class='enjoy-statement'>
          Let's enjoy 
          <p class='enjoy-statement-message'>
            CRAFT BEER
          <br>
             &
          <br>
             FUKUOKA
          <br>
          <p class='enjoy-statement-message2'>
          クラフトビールで福岡を彩ろう
          </p>
        </h4>
    </div>
  </div>
</div>

<%= render "devise/shared/footer" %>

<span id="back">
    <a href="">
      <%= image_tag 'top_btn.png', data: {"turbolinks"=>false}, class: "arrow" %>
    </a>
</span>